### ISSUE TITLE
Market goods durability variation missing

### ISSUE THREAD

**Issue by oagur39999** [jcsato/sato_expanded_markets_mod#1]
So installing this mod apparently makes towns and castles sell goods at full durability now, I can't see any low-mid durability items on sale in any town I've been at this save.

**Comment by jcsato** [comment]
I can reproduce this on my end - surprised it went unnoticed for so long. Will have a fix out soon, thanks for reporting.

**Comment by jcsato** [comment]
Fixed in 1.3: https://github.com/jcsato/sato_expanded_markets_mod/releases/tag/v1.3
